// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnANkoDRtTTiU0mWXGSDY9sV2hD41MJj0',
    appId: '1:281230189029:web:cc158a882cdfafc96f4f0c',
    messagingSenderId: '281230189029',
    projectId: 'fintracker-e7788',
    authDomain: 'fintracker-e7788.firebaseapp.com',
    storageBucket: 'fintracker-e7788.firebasestorage.app',
    measurementId: 'G-TPP98X6QNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXyyw0VYKUJbs8I-g61n-BU8i1N5BC_6k',
    appId: '1:281230189029:android:b6ba42c4364ec5bb6f4f0c',
    messagingSenderId: '281230189029',
    projectId: 'fintracker-e7788',
    storageBucket: 'fintracker-e7788.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnoP5aANyIsxaox9DLp0LtCGVaS20x5Yo',
    appId: '1:281230189029:ios:bcf3d1b2d7c352af6f4f0c',
    messagingSenderId: '281230189029',
    projectId: 'fintracker-e7788',
    storageBucket: 'fintracker-e7788.firebasestorage.app',
    iosBundleId: 'com.example.financeTrack',
  );
}
